// Tier A — grounding (common)
// Neutral, reread-safe, no emotional push
const tierA = [
  "nothing is urgent",
  "this moment is enough",
  "you can move slowly",
  "nothing needs to happen right now",
  "you can just breathe for a moment",
  "this is a small pause for you",
  "sometimes being still is enough",
  "the world can wait a little",
  "being here is enough",
  "there is no rush",
  "you are allowed to pause",
  "nothing bad is happening here",
  "this is enough for now",
  "nothing needs an answer right now",
  "you are safe in this moment",
  "this is a quiet place",
  "this moment can be soft",
  "nothing important is being missed",
  "nothing is expected of you",
  "you can breathe again",
  "this is not urgent",
  "you can take your time",
  "nothing dramatic is happening",
  "nothing is being optimized",
  "this can be easy for a moment",
  "nothing needs your attention right now",
  "this is allowed to be simple",
  "this is a low-pressure moment",
  "nothing needs solving",
  "this can stay unfinished",
  "you can be here without effort",
  "this moment is neutral",
  "nothing is pulling at you",
  "you can rest your attention",
  "this is a calm interval",
  "nothing is asking for action",
  "this space is unclaimed",
  "you can let things idle",
  "this moment does not hurry",
  "nothing requires a response",
  "you can stop scanning",
  "this can remain quiet",
  "nothing is at stake here",
  "this is a pause, not a gap",
  "nothing needs shaping",
  "you can leave things as they are",
  "this moment is uncomplicated",
  "nothing is pressing forward",
  "you can loosen your focus",
  "this is not a decision point",
  "nothing is being evaluated",
  "you can stay unremarkable",
  "this does not need momentum",
  "nothing is shifting suddenly",
  "you can exist without aim",
  "this moment has no task",
  "nothing is leaning on you",
  "this can be still without reason"
];
